version: '3.9'

services:
  gateway-service:
    build: './gateway-service'
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      ms-auth:
        condition: service_started
      ms-inventario:
        condition: service_started
      ms-proveedores:
        condition: service_started
    networks:
      - app-net

  ms-auth:
    build: './ms-auth'
    container_name: ms-auth
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/mesago_auth_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      db-mysql:
        condition: service_healthy
    networks:
      - app-net

  ms-inventario:
    build: ./ms-inventario
    container_name: ms-inventario
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/mesago_inventario?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      db-mysql:
        condition: service_healthy
    networks:
      - app-net

  ms-proveedores:
    build: ./ms-proveedores
    container_name: ms-proveedores
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/mesago_proveedores?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      db-mysql:
        condition: service_healthy
    networks:
      - app-net

  db-mysql:
    image: mysql:8.0
    container_name: db-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./create-databases.sh:/docker-entrypoint-initdb.d/create-databases.sh
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  mysql_data:

#services:
#  #Gateway Service:
#  gateway-service:
#    build: './gateway-service'
#    container_name: gateway-service
#    ports:
#      - "8080:8080"
#    depends_on:
#      - ms-auth
#      - ms-inventario
#      #- ms-clientes
#      - ms-proveedores
#      #- ms-facturacion
#      #- ms-reservas
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - app-net
#
#
#  #Auth services
#  ms-auth:
#    build: './ms-auth'
#    container_name: ms-auth
#    ports:
#      - "8081:8081"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/mesago_auth_db?useSSL=false&allowPublicKeyRetrieval=true
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#    depends_on:
#      - db-mysql
#    networks:
#      - app-net
#
#
##  ms-pedidos:
##    build: ./ms-pedidos
##    container_name: ms-pedidos
##    ports:
##      - "8082:8082"
##    environment:
##      - SPRING_PROFILES_ACTIVE=docker
##      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/pedidosdb?useSSL=false&allowPublicKeyRetrieval=true
##      - SPRING_DATASOURCE_USERNAME=root
##      - SPRING_DATASOURCE_PASSWORD=root
##    depends_on:
##      - db-mysql
##    networks:
##      - app-net
#
#
#  #Inventario Service
#  ms-inventario:
#    build: ./ms-inventario
#    container_name: ms-inventario
#    ports:
#      - "8083:8083"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/mesago_inventario?useSSL=false&allowPublicKeyRetrieval=true
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#    depends_on:
#      - db-mysql
#    networks:
#      - app-net
#
#
#  ms-proveedores:
#    build: ./ms-proveedores
#    container_name: ms-proveedores
#    ports:
#      - "8084:8084"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/mesago_proveedores?useSSL=false&allowPublicKeyRetrieval=true
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#    depends_on:
#      - db-mysql
#    networks:
#      - app-net
#
#
##  ms-facturacion:
##    build: ./ms-facturacion
##    container_name: ms-facturacion
##    ports:
##      - "8085:8085"
##    environment:
##      - SPRING_PROFILES_ACTIVE=docker
##      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/facturaciondb?useSSL=false&allowPublicKeyRetrieval=true
##      - SPRING_DATASOURCE_USERNAME=root
##      - SPRING_DATASOURCE_PASSWORD=12345
##    depends_on:
##      - db-mysql
##    networks:
##      - app-net
##
##
##  ms-clientes:
##    build: ./ms-clientes
##    container_name: ms-clientes
##    ports:
##      - "8086:8086"
##    environment:
##      - SPRING_PROFILES_ACTIVE=docker
##      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/clientesdb?useSSL=false&allowPublicKeyRetrieval=true
##      - SPRING_DATASOURCE_USERNAME=root
##      - SPRING_DATASOURCE_PASSWORD=12345
##    depends_on:
##      - db-mysql
##    networks:
##      - app-net
##
##
##  ms-reservas:
##    build: ./ms-reservas
##    container_name: ms-reservas
##    ports:
##      - "8087:8087"
##    environment:
##      - SPRING_PROFILES_ACTIVE=docker
##      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/reservasdb?useSSL=false&allowPublicKeyRetrieval=true
##      - SPRING_DATASOURCE_USERNAME=root
##      - SPRING_DATASOURCE_PASSWORD=12345
##    depends_on:
##      - db-mysql
##    networks:
##      - app-net
##
#
#  #Base de datos MySQL
#  db-mysql:
#    image: mysql:8.0
#    container_name: db-mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - "3307:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#    networks:
#      - app-net
#
#networks:
#   app-net:
#     driver: bridge
#
#volumes:
#  mysql_data: