version: "3.9"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data-volume:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - mesago-net


  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - ms-auth
      - ms-clientes
      - ms-facturacion
      - ms-inventario
      - ms-pedidos
      - ms-proveedores
      - ms-reservas
      - ms-catalogo-menu
    networks:
      - mesago-net

  ms-auth:
    build: ./ms-auth
    container_name: ms-auth
    restart: always
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/mesago_auth_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql-db
    networks:
      - mesago-net



  ms-clientes:
    build: ./ms-clientes
    container_name: ms-clientes
    restart: always
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/mesago_clientes
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql-db
    networks:
      - mesago-net



  ms-facturacion:
    build: ./ms-facturacion
    container_name: ms-facturacion
    restart: always
    environment:
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/mesago_facturacion
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql-db
    networks:
      - mesago-net



  ms-inventario:
    build: ./ms-inventario
    container_name: ms-inventario
    restart: always
    environment:
      - SERVER_PORT=8084
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/mesago_inventario
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql-db
    networks:
      - mesago-net



  ms-pedidos:
    build: ./ms-pedidos
    container_name: ms-pedidos
    restart: always
    environment:
      - SERVER_PORT=8085
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/mesago_pedidos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql-db
    networks:
      - mesago-net



  ms-proveedores:
    build: ./ms-proveedores
    container_name: ms-proveedores
    restart: always
    environment:
      - SERVER_PORT=8086
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/mesago_proveedores
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql-db
    networks:
      - mesago-net




  ms-reservas:
    build: ./ms-reservas
    container_name: ms-reservas
    restart: always
    environment:
      - SERVER_PORT=8087
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/mesago_reservas
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql-db
    networks:
      - mesago-net


  ms-catalogo-menu:
    build: ./ms-catalogo-menu
    container_name: ms-catalogo-menu
    restart: always
    environment:
      - SERVER_PORT=8088
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/mesago_menu
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql-db
    networks:
      - mesago-net


networks:
  mesago-net:
    driver: bridge

volumes:
  mysql-data-volume:
    driver: local


