server:
  port: 8080

jwt:
  secret: mesagosecretkeyultralargaparaquejwtnosequeje

springdoc:
  swagger-ui:
    urls:
      - name: Auth
        url: /v3/api-docs/auth
      - name: Clientes
        url: /v3/api-docs/clientes
      - name: Facturación
        url: /v3/api-docs/facturacion
      - name: Inventario
        url: /v3/api-docs/inventario
      - name: Pedidos
        url: /v3/api-docs/pedidos
      - name: Proveedores
        url: /v3/api-docs/proveedores
      - name: Reservas
        url: /v3/api-docs/reservas
      - name: Catálogo Menu
        url: /v3/api-docs/catalogo-menu
