server:
  port: 8080

jwt:
  secret: mesagosecretkeyultralargaparaquejwtnosequeje

springdoc:
  swagger-ui:
    urls:
      - name: ms-auth
        url: /v3/api-docs/auth
      - name: ms-clientes
        url: /v3/api-docs/clientes
      - name: ms-facturacion
        url: /v3/api-docs/facturacion
      - name: ms-inventario
        url: /v3/api-docs/inventario
      - name: ms-pedidos
        url: /v3/api-docs/pedidos
      - name: ms-proveedores
        url: /v3/api-docs/proveedores
      - name: ms-reservas
        url: /v3/api-docs/reservas
      - name: ms-catalogo-menu
        url: /v3/api-docs/catalogo-menu