server:
  port: 8080

spring:
  application:
    name: gateway-service

jwt:
  secret: mesagosecretkeyultralargaparaquejwtnosequeje

cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:5173

  allowed-headers:
    - Authorization
    - Content-Type