server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
     gateway:
       routes:

         -  id: ms-auth-route
            uri: lb://ms-auth
            predicates:
              - Path=/api/auth/**

         -  id: ms-users-route
            uri: lb://ms-auth
            predicates:
            - Path=/api/users/**, /api/admin/**

         -  id: ms-pedidos-route
            uri: lb://ms-pedidos
            predicates:
            - Path=/api/pedidos/**

         -  id: ms-inventario-route
            uri: lb://ms-inventario
            predicates:
            - Path=/api/inventario/**

         -  id: ms-clientes-route
            uri: lb://ms-clientes
            predicates:
            - Path=/api/clientes/**


jwt:
  secret: mesagosecretkeyultralargaparaquejwtnosequeje